security:
  password_hashers:
    Symfony\Component\Security\Core\User\InMemoryUser: plaintext
  providers:
    users_in_memory:
      memory:
        users:
          '%env(BASIC_USER_LOGIN)%': { password: '%env(BASIC_USER_PASSWORD)%', roles: [ 'ROLE_API' ] }
  firewalls:
    api:
      lazy: true
      http_basic:
        realm: Secured Area
  access_control:
    - { path: ^/, roles: ROLE_API }
