version: '3'

services:
  database:
    container_name: postgres
    build:
      context: .
      dockerfile: docker/database/DockerFile
#    volumes:
#      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
#  adminer:
#    container_name: postgres-admin
#    image: adminer
#    ports:
#      - "8080:8080"
#volumes:
#  database_data:
