version: '3.8'

services:
  database:
    container_name: postgres
    build:
      context: ./docker/database/
    ports:
      - "5432:5432"
    networks:
      app-network:
        ipv4_address: 172.25.0.10
  test_database:
    container_name: postgres_test
    build:
      context: ./docker/database/
    ports:
      - "5433:5432"
    networks:
      app-network:
        ipv4_address: 172.25.0.11
  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/symfony_docker
    depends_on:
      - database
      - test_database
    networks:
      app-network:
        ipv4_address: 172.25.0.12
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    links:
      - database
    volumes:
      - ./:/var/www/symfony_docker
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      app-network:
        ipv4_address: 172.25.0.13
networks:
  app-network:
    name: app-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
