version: '3'

services:
  database:
    container_name: postgres
    build:
      context: .
      dockerfile: docker/database/DockerFile
    ports:
      - "5432:5432"
  test_database:
    container_name: postgres_test
    build:
      context: .
      dockerfile: docker/database/DockerFile
    ports:
      - "5433:5432"

