api:
    resource: .
    type: api_platform
    prefix: /
    defaults:
        cache_headers:
            max_age: 0
            shared_max_age: 0
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]

